# fly.toml app configuration file generated for lingering-river-2260 on 2023-07-07T15:18:03+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lingering-river-2260"
primary_region = "ams"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
